<?php

use Laminas\View\View;

/**
 * @var $this View
 */
?>
<h1>Incluir Imóvel</h1>
<form method="post" action="<?= $this->url('cadastros', [
                              'controller' => 'imovel',
                              'action' => 'gravar'
                            ]) ?>">
  Descrição: <input type="text" name="descricao" autofocus="autofocus" value="<?= $this->imovel->descricao ?>">
  Endereço: <input type="text" name="endereco" value="<?= $this->imovel->endereco ?>">
  Valor: <input type="number" name="valor" value="<?= $this->imovel->valor ?>">
  <input type="hidden" name="matricula" value="<?= $this->imovel->matricula ?>">
  <input type="submit" value="gravar">
</form>
<span><?= $this->messages ?></span>

<a href="<?= $this->url('cadastros', [
            'controller' => 'imovel'
          ]) ?>">Voltar</a>