<?php

/**
 * @var $this Laminas\View\Renderer\PhpRenderer
 */
?>
<h1>Cadastro de Imóveis</h1>
<p><a href="<?= $this->url('cadastros', [
              'controller' => 'imovel',
              'action' => 'editar'
            ]) ?>">Novo imóvel</a></p>
<table>
  <thead>
    <tr>
      <th>Matrícula</th>
      <th>Descrição</th>
      <th>Endereço</th>
      <th>Valor</th>
    </tr>
  </thead>
  <tbody>
    <?= $this->partialLoop('imoveis.phtml', $this->imoveis) ?>
  </tbody>
</table>
<a href="<?= $this->url('cadastros') ?>">Voltar</a>